### ISSUE TITLE
組み合わせプランのスライドの横棒がSafariで表示されない

### ISSUE THREAD

**Issue by YomogiBeta** [mirucoma/hp#25]
webkit の記述が必要？

**Comment by YomogiBeta** [comment]
https://qiita.com/kakuta_yu/items/626d7feecf54e39f7127

により不可能...?

一応"-webkit-overflow-scrolling": "auto !important"を追加。ただし、iPhoneを持っていないので大丈夫になったかどうかは未確認

**Comment by kra8** [comment]
HPのリメイクのためClose
