### ISSUE TITLE
HPデザインレビュー

### ISSUE THREAD

**Issue by Noir-Loup** [mirucoma/hp#3]
Header
- [x] ロゴ画像を変更 (size・margin)

レスポンシブの挙動に関して
- [x] top
       993px - 1216px間の文字の改行
- [x] 機能紹介
       選択リストのサイズは変更せずに、スライド側のみ可変
- [x] 利用料金
        577px - 1095px間の文字の改行
※ 文字の改行は、文字サイズを段階的に小さくする or ブレークポイントを新たに追加して、要素の間隔を変更

間隔の調整
- [x] メリット部分のカード内の箇条書きのleft-marginを16.25px→24pxに変更

**Comment by YomogiBeta** [comment]
レビューありがとうございます！
現在、機能紹介部分以外の全ての修正レビューは反映できたのですが、機能紹介の部分のみ、少しイメージが湧いていません、、。選択リストのサイズを固定（選択リストの親divにwidth: 320pxとmin-width: 320pxを指定)をすると下記の画像のように選択リストが画面外に出ていってしまいます、、。

選択リストとスライドはflexで横並びにしています。
お時間ある時で大丈夫ですので、対処法をご教授いただけないでしょうか、、。
また、もし自分のレビューの解釈が間違っている場合、お手数をおかけしますが、ご指摘いただけると幸いです。
よろしくお願いいたします！！

![how](https://user-images.githubusercontent.com/46161490/169271892-935a7ed4-edef-4c60-80c6-6700eb47ee89.gif)

**Comment by YomogiBeta** [comment]
complete
